### ISSUE TITLE
Bug when used with Nuxt (generating static files)

### ISSUE THREAD

**Issue by gtso86** [MMF-FE/vue-svgicon#21]
Hello, I'm using your awesome plugin with Nuxt and when I try to generate static files I receive this error and the page I include `<svgicon>` isn't rendered.

```
==== Error report ====
Route: '/account/login'
ReferenceError: document is not defined
    at o (PATH/admin-nuxt/node_modules/vue-svgicon/dist/index.js:1:2371)
    at r (PATH/admin-nuxt/node_modules/vue-svgicon/dist/index.js:1:2193)
    at t.exports (PATH/admin-nuxt/node_modules/vue-svgicon/dist/index.js:1:3814)
    at Object.<anonymous> (PATH/admin-nuxt/node_modules/vue-svgicon/dist/index.js:1:932)
    at e (PATH/admin-nuxt/node_modules/vue-svgicon/dist/index.js:1:324)
    at VueComponent.r (PATH/admin-nuxt/node_modules/vue-svgicon/dist/index.js:1:760)
    at callHook (PATH/admin-nuxt/node_modules/vue/dist/vue.runtime.common.js:2663:21)
    at VueComponent.Vue._init (PATH/admin-nuxt/node_modules/vue/dist/vue.runtime.common.js:4220:5)
    at new VueComponent (PATH/admin-nuxt/node_modules/vue/dist/vue.runtime.common.js:4394:12)
    at createComponentInstanceForVnode (PATH/admin-nuxt/node_modules/vue-server-renderer/build.js:6817:10)
    at renderComponentInner (PATH/admin-nuxt/node_modules/vue-server-renderer/build.js:6993:40)
    at renderComponent (PATH/admin-nuxt/node_modules/vue-server-renderer/build.js:6968:5)
    at RenderContext.renderNode (PATH/admin-nuxt/node_modules/vue-server-renderer/build.js:6884:5)
    at RenderContext.next (PATH/admin-nuxt/node_modules/vue-server-renderer/build.js:2189:14)
    at cachedWrite (PATH/admin-nuxt/node_modules/vue-server-renderer/build.js:2049:9)
    at renderElement (PATH/admin-nuxt/node_modules/vue-server-renderer/build.js:7108:5)
```

I also having other problems ([reported here](https://github.com/nuxt/nuxt.js/issues/1405#issuecomment-323170650)) and I thinking is caused by something inside the `vue-svgicon`.

Could you help me? Thanks in advance!

**Comment by Allenice** [comment]
https://github.com/MMF-FE/vue-svgicon#work-on-server-side-render-ssr  @gtso86
